### ISSUE TITLE
Changer couleur focus highlight

### ISSUE THREAD

**Issue by zwergon** [zwergon/grav-tsc#1]
Le bouton "dite m'en plus" et les onglets "portfolio, team, ..." utilise un jaune pour le highlight. 
Ce serait bien de faire un contraste de couleur pour ces boutons qui reprenne le thème de "sur" dans le logo "Théâtre Sur Cour"

**Comment by zwergon** [comment]
Il y a aussi la couleur du cadre qui peut être utilisée:
#f8bcbc
Autrement le rouge est effectivement:
#800000

A essayer de voir si on peut faire un truc avec la couleur plus claire du cadre. Sinon, il faudrait peut être revoir 2, 3 trucs dans le fonctionnement.

**Comment by MaxenceG2M** [comment]
Avec la couleur du cadre (`#f8bcbc`) :
![image](https://user-images.githubusercontent.com/4601728/194572523-733c0b4d-afdb-4a60-b5dd-4fea6c336486.png)

**Comment by zwergon** [comment]
C'est pas mal, non ?

**Comment by MaxenceG2M** [comment]
Je trouve ça un peu palot :s
