### ISSUE TITLE
Rajouter une rubrique contact à la fin

### ISSUE THREAD

**Issue by zwergon** [zwergon/grav-tsc#3]
Pour l'instant, il n'y a plus de rubrique contact. Il faudrait la rajouter pour que les gens puissent nous joindre par mail.
C'est quand même grâce à cela qu'on a été joué au Puy En Velay.

**Comment by MaxenceG2M** [comment]
Hello Jef,

Pour le côté Website : assez facile. Il me reste à peaufiner la partie présentation.
Je suis partie sur un classique "nom", "mail", "votre message".

Côté technique : 
* Pour utiliser le SMTP OVH, il faut s'authentifier avec une adresse mail @theatresurcour.fr --> j'ai créé la boite "website" dans ce but
* Le mail serait envoyé d'une adresse "noreply@theatresurcour.fr" (`from`). On peut mettre - côté OVH - un répondeur sur cette adresse si on le souhaite si on veut être fin du fin.
* Le mail serait envoyé à "jef@theatresurcour.fr" ET au mail du destinataire.
* --> Le mail "jef@theatresurcour.fr" apparaitrait donc pour le destinataire

En bref :
![image](https://user-images.githubusercontent.com/4601728/194728250-70882f8f-444e-428b-89ac-2e31d063fca3.png)

**Comment by MaxenceG2M** [comment]
Un aperçu :

![image](https://user-images.githubusercontent.com/4601728/194731918-d0c12092-9ca4-4ecf-a421-fdf25be51223.png)

J'ai pris une photo de Une preuve que j'avais sous la main.
Si OK pour toi je merge / push :)

**Comment by MaxenceG2M** [comment]
Roh c'est quand même bien foutu !
J'ai reçu un mail de GitHub (toi aussi peut-être) qui a détecté que j'avais mis le mot de passe en clair dans le code !

C'est fait sciemment : au niveau de Grav pas moyen de faire autrement, pour la simple raison qu'il faut le mot de passe en clair pour communiquer avec le SMTP.

Je ne sais pas si il y a moyen de faire quelque chose au niveau du déploiement pour templatiser le fichier et utiliser un secret.

**Comment by zwergon** [comment]
Pour le passwd en clair, voila la réponse de grav:
https://github.com/getgrav/grav-plugin-email/issues/27

A priori tu as crée un compte smtp dédié. Donc, ça parait tout bon :-)

**Comment by zwergon** [comment]
> Un aperçu :
> 
> ![image](https://user-images.githubusercontent.com/4601728/194731918-d0c12092-9ca4-4ecf-a421-fdf25be51223.png)
> 
> J'ai pris une photo de Une preuve que j'avais sous la main. Si OK pour toi je merge / push :)

C'est bon pour moi, go pour le merge.

**Comment by MaxenceG2M** [comment]
Pushé sur main
