### ISSUE TITLE
Un lien pour downloader le dossier de presse

### ISSUE THREAD

**Issue by zwergon** [zwergon/grav-tsc#5]
Dans le popup qui s'ouvre pour chaque projet, on va rajouter un lien pour télécharger le dossier.
Un peu comme sur jimdo

![image](https://user-images.githubusercontent.com/6973203/193465064-a8077d3f-8f73-42e9-8ee3-7bde97041ee4.png)

**Comment by MaxenceG2M** [comment]
Branche feature/press_kit :
![image](https://user-images.githubusercontent.com/4601728/194599786-6c71d9f5-d78c-40d0-95c9-20c832ddbcf4.png)

Je n'ai pas traité d'autres types de fichier que le PDF.

Ok pour toi ?

**Comment by zwergon** [comment]
Oui, c'est parfait pour moi. Je rajouterai les différents dossiers que j'ai pour chaque projet. Et je complèterai les `press_kit`.

**Comment by MaxenceG2M** [comment]
C'est pushé !
Commit f5d08b2e1352cbb6f5e535f2c60f57d7b5efa3d5
